# Site settings
title: TAKU'S Dev Dairy
description: "Dev Diary"
baseurl: ""
url: "https:leehongtaek.githu.io"
# User settings
username: Hongtaek Lee
user_title: Rookie Developer
email: taekganzi@gmail.com
twitter_username: "taekganzi"
github_username:  leehongtaek
gplus_username:  "taekganzi"
disqus_username: "leehongtaek"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: JETRO n Kawasaki Heavy Industries
    url: https://github.com/
  - name: KOSTA108
    url: https://github.com/
  - name: SangAh ManagementColsulting
    url: https://github.com/ 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
